[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "pgame_simple"
version = "0.1.1"
authors = [
  { name="MRanos"},
]
description = "a framework based on pygame"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
