[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "0.0.7"
name = "sukta"

dependencies = [
    # core
    "numpy",
    "scipy",
    "dill",
    # plot
    "plotly",
    "kaleido",
    "matplotlib",
    # trackers
    "rich",
    "aim",
    "tensorflow-cpu",
]

requires-python = ">= 3.10"

authors = [
    {name = "akrishna"},
]
maintainers = [
    {name = "akrishna"},
]
description = "Personalized training loop utilities for ML, RL, Robotics"
readme = "README.md"
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

keywords = ["utility", "common loop utility", "slurm utility"]

[tool.bumpver]
current_version = "0.0.7"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"sukta/__init__.py" = [
    '__version__ = "{version}"',
]

[tool.isort]
profile = "black"

[project.optional-dependencies]
dev = [
    "bumpver",
    "build",
    "twine",
    "isort",
    "black",
    "pre-commit",
    "pytest",
]
torch = [
    "torch",
    "torchvision",
]
rl = [
    "zarr",
    "imagecodecs",
    "numba",
]