[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "booklet"
version = '0.1.8'
description = "A python key-value file database"
readme = "README.rst"
license = "Apache-2.0"
authors = [
    { name = "Mike Kittridge", email = "mullenkamp1@gmail.com" },
]
keywords = [
    "dbm",
    "shelve",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/mullenkamp/booklet"

[tool.hatch.build.targets.sdist]
include = [
    "/booklet",
]

