[tool.poetry]
name = "notdiamond"
version = "0.1.0-alpha.19"
description = "NotDiamond Python Library"
authors = ["Tze-Yang Tung"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.0"
langchain = "0.1.3"
anthropic = "0.12.0"
pydantic = "2.5.3"
datasketch = "1.6.4"
langchain-google-genai = "^0.0.6"
litellm = "^1.22.3"
langchain-openai = "^0.0.5"
langchain-community = "^0.0.19"
python-dotenv = "^1.0.1"
openai = "^1.13.3"

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.350"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
