[tool.poetry]
name = "pcm_player"
version = "0.3.0"
description = ""
authors = ["MattEqualsCoder <mattequalscoder@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
soundfile = ">=0.12.1"
sounddevice = ">=0.4.6"
numpy = ">=1.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pcm_player = 'pcm_player.__main__:cli'