[tool.poetry]
name = "ticton"
version = "0.1.29"
description = ""
authors = ["alan890104 <alan890104@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
aiohttp = "^3.9.3"
tonsdk = "1.0.13"
tonpy = "0.0.0.1.2b0"
tvm-valuetypes = "^0.0.12"
pytoncenter = "0.0.14"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry_bumpversion.file."ticton/__init__.py"]
