[build-system]
requires = [
    "setuptools >= 48",
    "setuptools_scm >= 6.2",
    "wheel >= 0.29.0",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:",
]

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.messages_control]
disable = """
fixme,
missing-class-docstring,
missing-function-docstring,
missing-module-docstring,
"""

[tool.pytest.ini_options]
addopts = "-vvv --cov=nubium_utils --cov-report term-missing --cov-branch --no-cov-on-fail --cov-fail-under=10"
filterwarnings = "ignore:the imp module is deprecated in favour of importlib.*:DeprecationWarning:venusian:"
testpaths = ["tests"]

[tool.setuptools_scm]
local_scheme = "no-local-version"