[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sdlv_api_client"
dynamic = ["version"]
description = "API Client Base class"
readme = "README.md"
requires-python = "~=3.10"
license = { file = "LICENSE" }
keywords = ["api", "client", "api-client"]
authors = [
  { name = "Eriks Karls", email = "git@72.lv" },
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "httpx[http2]~=0.27.0",
  "pydantic~=2.6",
]


[project.urls]
"Homepage" = "https://pypi.org/project/sdlv-api-client/"
"Bug Reports" = "https://git.72.lv/eriks/api_client/issues"
"Funding" = "https://donate.pypi.org"
"Source" = "https://git.72.lv/eriks/api_client"


[tool.setuptools.dynamic]
version = { attr = "api_client.__version__" }


[tool.bumpversion]
current_version = "1.1.1"
commit = true
tag = true
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
message = "Bump version: {current_version} → {new_version}"


[[tool.bumpversion.files]]
filename = "src/api_client/__init__.py"


[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''(
    | .git/*
)'''
workers = 4


[tool.isort]
profile = "black"
line_length = 120
skip = ["migrations", "env", "venv", ".venv", ".git", "media"]


[tool.mypy]
python_version = "3.11"
exclude = ['^\.?venv/',]
plugins = ["pydantic.mypy"]
warn_unused_configs = true
disallow_untyped_defs = true
implicit_optional = true
warn_redundant_casts = true
warn_no_return = false
ignore_missing_imports = false
