
[build-system]
requires = ["setuptools"] 
build-backend = "setuptools.build_meta" 


[project]
name = "rerankers" 


version = "0.0.1post1"

description = "A unified API for various document re-ranking models."

readme = "README.md"

requires-python = ">=3.8"

license = {file = "LICENSE.txt"}

keywords = ["reranking", "retrieval", "rag", "nlp"]

authors = [
  {name = "Ben Clavié", email = "ben@clavie.eu" }
]
maintainers = [
  {name = "Ben Clavié", email = "ben@clavie.eu" }
]

classifiers = [

  # Specify the Python versions you support here. In particular, ensure
  # that you indicate you support Python 3. These classifiers are *not*
  # checked by "pip install". See instead "requires-python" key in this file.
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "pydantic",
  "tqdm",
]

[project.optional-dependencies]
all = ["transformers", "torch", "litellm", "requests"]
transformers = ["transformers", "torch"]
t5 = ["transformers", "torch", "sentencepiece", "protobuf"]
api = ["requests"]
gpt = ["litellm"]
training = ["inranker", "sentence-transformers"]
dev = ["ruff", "isort", "pytest"]

[project.urls]
"Homepage" = "https://github.com/bclavie/rerankers"