[tool.poetry]
name = "keel_ds"
version = "0.1.10"
description = ""
authors = ["Maicondalllg <maicon.dallagnol@unesp.br>"]
readme = "README.md"


packages = [{include = "keel_ds"}]
include = ["keel_ds/data/balanced/processed/*", "keel_ds/data/imbalanced/processed/*"]


[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
