[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools]
py-modules = []

[project]
name = "amcess2024"
version = "0.1.2"
dependencies = [
    "attrs>=23.2.0",
    "scipy>=1.12.0",
    "numpy==1.23.1",
    "pyscf>=2.5.0",
    "h5py>=3.1.0",
    "pyberny>=0.6.3",
    "geomeTRIC>=0.9.7.2",
    "GPyOpt>=1.2.6",
    "pyDOE>=0.3.8",
    "matplotlib>=3.8.3",
    "matplotlib-inline>=0.1.6",

]
requires-python = ">=3.9"
authors = [
    { name = "Edison Florez", email = "edisonffhc@gmail.com" },
    { name = "Andy Zapata", email = "danianescobarv@gmail.com" },
    { name = "Daniel Bajac" },
    { name = "Alejandra Mendez" },
    { name = "Cesar Ibarguen" },
    { name = "Jos√© Aucar" },
]
maintainers = [
    { name = "Edison Florez", email = "edisonffhc@gmail.com" },
    { name = "Andy Zapata", email = "danianescobarv@gmail.com" },
]
description = "Atomic and Molecular Cluster Energy Surface Sampler"
readme = "README.md"
license = { file = "LICENSE" }
keywords = [
    "Atomic Cluster",
    "Molecular Cluster",
    "optimization",
    "Potential Energy Surface",
    "PES",
    "Monte Carlo",
    "Simulated Annealing",
    "Bayesian Optimization",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
]

[project.urls]
homepage = "https://github.com/e-florez/amcess"
Source = "https://github.com/e-florez/amcess"
