[package]
name = "reverse-geocoder-test"
version = "0.1.3"
edition = "2021"

[lib]
name = "reverse_geocoder_test"
crate-type= ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module", "abi3-py38"] }
pyo3-polars = { version = "0.12.0", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
polars = { version = "0.38.2", default-features = false }
polars-arrow = { version = "0.38.2", default-features = false }
polars-core = { version = "0.38.2", default-features = false }
reverse_geocoder = "4.1.1"


[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
