[tool.poetry]
name = "fzstats"
version = "0.1.0"
description = ""
authors = ["Mingfeng Yu <mfdevworld@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
fzstats = "fzstats.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.9.0"}

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
ipython = "^8.22.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
