[project]
name = "emploid"
version = "0.0.7"
authors = [
  { name="twyyre", email="twyyre1996@gmail.com" },
]
description = "Emploid is a simple open-source automation framework for automating web and android activities."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/twyyre/emploid"
Issues = "https://github.com/twyyre/emploid/issues"