[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "denkproto"
requires-python = ">=3.10"
version = "0.1.0"
dependencies = [
    "protobuf==3.20.3"
]

[tool.hatch.build.targets.wheel]
packages = ["src/denkproto"]
