[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "baguette-verse"
version = "1.8.8"
authors = [
  { name="Vincent Raulin", email="vincent.raulin@inria.fr" },
]
description = "A malware behavioral analysis framework centered around BAGUETTE!"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
]
dependencies =  [
  "viper_lib>=1.5.2",
  "boa_lib>=1.2",
  "python-magic; platform_system != 'Windows'",
  "python-magic-bin; platform_system == 'Windows'",
  "Levenshtein"
]

[project.scripts]
bake = "baguette.bakery.bake:main"
metalib = "baguette.croutons.metalib.interact:main"
toast = "baguette.croutons.toast:main"

baguette = "baguette.baguette:main"

"baguette.bake" = "baguette.bakery.bake:main"
"baguette.metalib" = "baguette.croutons.metalib.interact:main"
"baguette.toast" = "baguette.croutons.toast:main"

"baguette.tutorial" = "baguette.tutorial.scripts:start"
"baguette.tutorial.reset" = "baguette.tutorial.scripts:reset"
"baguette.tutorial.status" = "baguette.tutorial.scripts:status"
"baguette.tutorial.help" = "baguette.tutorial.scripts:help"
"baguette.tutorial.samples" = "baguette.tutorial.scripts:copy_reports"

[tool.hatch.build]
include = [
  "*.py",
  "*.zip",
  "*.json",
  "baguette/tutorial/state.txt",
]

[project.urls]
"Repository" = "https://gitlab.inria.fr/vraulin/baguette-verse"
"Bug Tracker" = "https://gitlab.inria.fr/vraulin/baguette-verse/-/issues"