[tool.poetry]
authors = ["Daniel CAUNE <daniel.caune@gmail.com>"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
]
description = "Xebus SIS Connector Core Python Library"
keywords = ["connector", "core", "library", "sis", "xebus"]
license = "SEE LICENSE IN <LICENSE.md>"
name = "xebus-sis-connector-core-library"
packages = [{ include = "majormode", from = "src" }]
readme = "README.md"
repository = "https://github.com/xebus/xebus-sis-connector-core-python-library"
version = "1.3.3"

[tool.poetry.dependencies]
perseus-core-library = "^1.20.0"
python = "^3.9"
unidecode = "^1.3.8"
xebus-core-library = "^1.4"
xebus-family-data-library = "^1.0.2"

[tool.poetry.dev-dependencies]
setuptools = "^69.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
