[tool.poetry]
name = "syneto_api"
version = "0.2.57"
description = "Syneto Client API library"
authors = ["Syneto <developers@syneto.eu>"]
license = "Proprietary"
homepage = "https://github.com/SynetoNet/syneto-api"
repository = "https://github.com/SynetoNet/syneto-api"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.16"
requests = {extras = ["secure"], version = "^2.25"}
inflection = "^0.5"
aiohttp = "^3.8"
aiodns = "^3"
tenacity = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
ipdb = "^0.13.7"
pytest-asyncio = "^0.15"
black = {version = "^21.6b0", allow-prereleases = true}
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
