[build-system]
requires = ["requests", "PySimpleGUI", "pyautogui", "hatchling"]
build-backend = "hatchling.build"

[project]
name = "meowerclient"
version = "1.5"
authors = [
    { name="SpeedBee411" },
]
description = "A Python client to view the 25 most recent Meower posts, now with full message viewing at the user's discretion!"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Scratchy2/meowerclient/tree/main"
Issues = "https://github.com/Scratchy2/meowerclient/issues"

[tool.hatch.build.targets.wheel]
packages = ["requests", "PySimpleGUI", "pyautogui"]