[tool.poetry]
name = "dumbo-runlim"
version = "0.2.2"
description = "A CLI to run and limit processes (and their subprocesses)"
authors = ["Mario Alviano <mario.alviano@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dumbo-utils = "^0.3.0"
psutil = "^5.9.7"
dumbo-asp = "^0.3.6"
xasp = "^0.8.3"


[tool.poetry.dev-dependencies]
pytest = "^8.1.1"
coverage = "^7.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
