[tool.poetry]
name = "mikrotikapi"
version = "0.4.1"
description = ""
authors = ["goltsev <mark@goltsev.net>"]
readme = "README.md"
packages = [{ include = "mikrotikapi" }]
exclude = ["tests/*", "**/tests/*", "docs/*", "**/docs/*"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.9.3"
requests = "^2.31.0"
requests-toolbelt = "^1.0.0"
pydantic = "^2.6.3"
flake8 = "^7.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
pylint = "^3.0.3"
black = "^24.2.0"
ipython = "^8.22.1"
pytest-asyncio = "^0.23.5"
bump-pydantic = "^0.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 79
target-version = ['py311']
#skip-string-normalization = true

[tool.pylint]
line-length = 79

[tool.pytest.ini_options]
#filterwarnings = [
#    "default"
#]

#
